FORMAT: 1A
HOST: http://www.polaride.com/

# Polaride

A car polling application

## User [/mobile/user]

### √ Login [POST]

The user will be created if does not exist in the system. The same client_id is returned and a session cookie is set if successful.

+ Request (application/json)

        {
            "loginMethod": "facebook",
            "userId": "user_id",
            "userToken": "user_token"
        }

+ Response 200 (application/json)

    + Headers
    
            set-cookie: polarride=session_cookie; Secure;

    + Body

            {
                "userId": "user_id",
                "email": "daniel@polaride.com",
                "session": true
            }
            
+ Response 401 (application/json)

    + Headers
    
            Set-Cookie: polarride=null; Secure;

    + Body

            {
                "userId": "user_id",
                "session": false
            }

### Register [PUT]



### √ Logout [DELETE]

Session is destroyed on logout.

+ Response 200 (application/json)

    + Headers
    
            Set-Cookie: polarride=null; Secure;
            
    + Body

            {
                "clientId": "client_id"
                "session": false
            }

### √ Check Session [GET]

Check if the session is open with polaride server. A closed session requires login.

+ Response 200 (application/json)

        {
            "session": false
        }
        
## Schedule [/schedule]

### Get My Schedule [GET]

+  Request 200 (application/json)
        { 
            "passengerID": "1626730954323019",
            "number_of_seat": 1,
            "flexibility_early": 1470728606.856591,
            "fromLatitude": 49.28239320918291,
            "flexibility_late": 1470729206.856591,
            "time": 1470728906.856591,
            "passenger_fare": 3.9,
            "toLatitude": 49.23278406018312,
            "driver_fare": 3.22,
            "fromLongitude": -123.1185486540198,
            "toLongtitude": -123.1270847842097,
            "type": "Need a ride" 
        }