FORMAT: 1A
HOST: http://www.polaride.com/

# Polaride

A car polling application

## User [/user]

### √ Login [POST /user/mobile/login]

+ Request (application/json)

        {
            # can be 'facebook', 'google', 'twitter', or 'polaride'
            "loginMethod": "facebook",
            # if using social loginMethod
            "userId": "user_id",
            "userToken": "user_token",
            # if using polaride loginMethod
            "email": "user_id",
            "password": "user_token"
        }

+ Response 200 (application/json)

    + Headers
    
            set-cookie: polarride=session_cookie; Secure;

    + Body

            {
                "userId": "user_id",
                "email": "daniel@polaride.com",
                "phoneNumber": "1234561234",
                "homeAddress": "6808 Inverness St. Vancouver",
                "workAddress": "555 W Hastings Vancouver",
                "session": true
            }
            
+ Response 401 (application/json)

    + Headers
    
            Set-Cookie: polarride=null; Secure;

    + Body

            {
                "session": false,
                # if using social
                "userId": "user_id",
                # if using polaride
                "email": "daniel@polaride.com"
            }

### √ Polaride Signup [POST /user/mobile/signup]

+ Request (application/json)

        {
            "email": "daniel@polaride.com",
            "password": "encrypted_string",
            "phoneNumber": "1234561234"
        }

+ Response 200 (application/json)

    + Headers
    
            set-cookie: polarride=session_cookie; Secure;

    + Body

            {
                "userId": "user_id",
                "email": "daniel@polaride.com",
                "phoneNumber": "1234561234",
                "homeAddress": "6808 Inverness St. Vancouver",
                "workAddress": "555 W Hastings Vancouver",
                "session": true
            }
            
+ Response 401 (application/json)

    + Headers
    
            Set-Cookie: polarride=null; Secure;

    + Body

            {
                "email": "daniel@polaride.com",
                "session": false
            }

### √ Profile updates [PUT]

+ Request (application/json)

        {
            "userId": "user_id",
            # can be any one of these fields or more
            "phoneNumber": "1234561234",
            "homeAddress": "6808 Inverness St. Vancouver",
            "workAddress": "555 W Hastings Vancouver"
        }

+ Response 200 (application/json)

    + Body

            {
                "userId": "user_id",
                # returns only the fields in the request
                "phoneNumber": "1234561234",
                "homeAddress": "6808 Inverness St. Vancouver",
                "workAddress": "555 W Hastings Vancouver"
            }
            
+ Response 401 (application/json)

    + Body

            {
                "userId": "user_id"
            }

### √ Logout [DELETE]

+ Response 200 (application/json)

    + Headers
    
            Set-Cookie: polarride=null; Secure;
            
    + Body

            {
                "userId": "user_id",
                "session": false
            }

### √ Check Session [GET]

+ Response 200 (application/json)

        {
            "session": false
        }

### √ Register as a Driver [POST /user/driver]

+ Request (application/json)

        {
            "regNumber": "TBA 100",
            "color": "pink",
            "model": "Toyota Prius C",
            "seats": 4,
            "year": 2015
        }

+ Response 200 (application/json)

    + Body

            {
                "userId": "user_id",
                "driver": true
            }

## Schedule [/schedule]

### √ Get My Rides [GET /schedule/rides/{:id}]
        
+ Response 200 (application/json)

        {
            "_id": "MongoID"
            "passengerID": "54321",
            "driverID": "12345",
            "type": "request",
            "seats": 1,
            "time": 1470728906.856591,
            "flexibility": {
                "early": 1470728906.856591,
                "late": 1470728906.856591
            },
            "origin": {
                "latitude": 49.28239320918291,
                "longtitude": -123.1185486540198
            },
            "destination": {
                "latitude": 49.28239320918291,
                "longtitude": -123.1185486540198
            },
            "fare": {
                "passenger": 3.90,
                "driver": 3.22
            }
        }
        
### √ Get My Offers [GET /schedule/offers/{:id}]
        
+ Response 200 (application/json)

        {
            "_id": "MongoID",
            "driverID": "12345",
            "type": "offer",
            "requests": [{
                "id": "requestID_1",
                "passengerID": "54321"
            },
            {
                "id": "requestID_2",
                "passengerID": "54320"
            }],
            "seats": 1,
            "time": 1470728906.856591,
            "flexibility": {
                "early": 1470728906.856591,
                "late": 1470728906.856591
            },
            "origin": {
                "latitude": 49.28239320918291,
                "longtitude": -123.1185486540198
            },
            "destination": {
                "latitude": 49.28239320918291,
                "longtitude": -123.1185486540198
            },
            "fare": {
                "passenger": 3.90,
                "driver": 3.22
            }
        }

### √ Make a Ride Request [POST /schedule/rides]

+ Request (application/json)

        {
            "passengerID": "54321",
            "type": "request",
            "seats": 1,
            "time": 1470728906.856591,
            "flexibility": {
                "early": 1470728906.856591,
                "late": 1470728906.856591
            },
            "origin": {
                "latitude": 49.28239320918291,
                "longtitude": -123.1185486540198
            },
            "destination": {
                "latitude": 49.28239320918291,
                "longtitude": -123.1185486540198
            },
            "fare": {
                "passenger": 3.90,
                "driver": 3.22
            }
        }

+ Response 200 (application/json)

        {
            "userId": "user_id",
            "status": "requested"
        }

### √ Make a Ride Offer [POST /schedule/offers]

+ Request (application/json)

        {
            "driverID": "12345",
            "type": "offer",
            "seats": 4,
            "time": 1470728906.856591,
            "flexibility": {
                "early": 1470728906.856591,
                "late": 1470728906.856591
            },
            "origin": {
                "latitude": 49.28239320918291,
                "longtitude": -123.1185486540198
            },
            "destination": {
                "latitude": 49.28239320918291,
                "longtitude": -123.1185486540198
            }
        }

+ Response 200 (application/json)

        {
            "userId": "user_id",
            "status": "offered"
        }